# Merge the .csv files with European Capital and cities with >100k population

Merge the `cities/development/european_capitals.csv` created previously and the `cities/development/european_100000pop.csv` created with `extract_data_from_un_source.ipynb` and `check_polygons.ipynb`.

## Setup

In [1]:
%run -i "functions.py"

## Load cities

In [ ]:
capitals = pd.read_csv(
    "../cities/development/european_capitals.csv",
    sep = ";"
)

cities_100000pop = pd.read_csv(
    "../cities/development/european_100000pop.csv",
    sep = ";"
)

               name_en   country_en    nominatim_query alpha-2  population
0               Aachen      Germany             Aachen      DE      247380
1      Aix-En-Provence       France    Aix-En-Provence      FR      142668
2    Alcalá De Henares        Spain  Alcalá De Henares      ES      195570
3             Alchevsk      Ukraine           Alchevsk      UA      105580
4           Alcobendas        Spain         Alcobendas      ES      116895
..                 ...          ...                ...     ...         ...
355       Zielona Góra       Poland       Zielona Góra      PL      141631
356         Zoetermeer  Netherlands         Zoetermeer      NL      124025
357             Zurich  Switzerland             Zurich      CH      423193
358             Zwolle  Netherlands             Zwolle      NL      123861
359           Šiauliai    Lithuania           Šiauliai      LT      100653

[360 rows x 5 columns]

## Retrieve population and alpha-2 code for european capitals

In [ ]:
un_list = pd.read_csv(
    "../cities/development/world_100000pop.csv",
    sep = ";"
).query("continent == 'Europe'").query("is_capital == True")
un_list.at[3566, 'city'] = "Warsaw"
un_list.at[3579, 'city'] = "Bucharest"
un_list.at[3499, 'city'] = "Luxembourg"
un_list.at[3836, 'city'] = "Bern"
un_list.at[3254, 'city'] = "Vienna"
un_list.at[3447, 'city'] = "Reykjavík"
un_list.at[3293, 'city'] = "Prague"
un_list.at[3431, 'city'] = "Athens"
un_list.at[3298, 'city'] = "Copenhagen"
un_list.at[3753, 'city'] = "Belgrade"
un_list.at[3575, 'city'] = "Lisbon"
un_list.at[3482, 'city'] = "Rome"
un_list.at[3272, 'city'] = "Brussels"
un_list

,continent,country,city,is_capital,population
3248,Europe,Albania,Tirana,True,418495
3254,Europe,Austria,Vienna,True,1897491
3262,Europe,Belarus,Minsk,True,2020133
3272,Europe,Belgium,Brussels,True,174383
3281,Europe,Bulgaria,Sofia,True,1221785
3287,Europe,Croatia,Zagreb,True,790017
3293,Europe,Czechia,Prague,True,1301432
3298,Europe,Denmark,Copenhagen,True,638790
3301,Europe,Estonia,Tallinn,True,437817
3303,Europe,Finland,Helsinki,True,656920
3338,Europe,France,Paris,True,2206488
3353,Europe,Germany,Berlin,True,3644826
3431,Europe,Greece,Athens,True,664046
3439,Europe,Hungary,Budapest,True,1737026
3447,Europe,Iceland,Reykjavík,True,129964
3449,Europe,Ireland,Dublin,True,544107
3482,Europe,Italy,Rome,True,2759629
3494,Europe,Latvia,Riga,True,614618
3498,Europe,Lithuania,Vilnius,True,546155
3499,Europe,Luxembourg,Luxembourg,True,128494
3500,Europe,Montenegro,Podgorica,True,185937
3505,Europe,Netherlands (Kingdom Of The),Amsterdam,True,821752
3532,Europe,North Macedonia,Skopje,True,546824
3533,Europe,Norway,Oslo,True,681067
3566,Europe,Poland,Warsaw,True,1792692
3575,Europe,Portugal,Lisbon,True,545142
3578,Europe,Republic Of Moldova,Chișinău,True,339079
3579,Europe,Romania,Bucharest,True,1722865
3654,Europe,Russian Federation,Moskva,True,11918057
3753,Europe,Serbia,Belgrade,True,1382045
3758,Europe,Slovakia,Bratislava,True,435296
3760,Europe,Slovenia,Ljubljana,True,285604
3796,Europe,Spain,Madrid,True,3277451
3831,Europe,Sweden,Stockholm,True,789024
3836,Europe,Switzerland,Bern,True,134290
3861,Europe,Ukraine,Kyiv,True,2910994
3898,Europe,United Kingdom Of Great Britain And Northern I...,London,True,8135667

In [12]:
print(set(un_list['city']) - set(capitals['name_en'])) # Just Moscow

{'Moskva'}

In [16]:
capitals["alpha-2"] = capitals["country_en"].map(get_alpha2)
capitals

             name_en              country_en           nominatim_query alpha-2
0          Amsterdam             Netherlands  Amsterdam, North Holland      NL
1   Andorra la Vella                 Andorra          Andorra la Vella      AD
2             Athens                  Greece    Municipality of Athens      GR
3           Belgrade                  Serbia                  Belgrade      RS
4             Berlin                 Germany                    Berlin      DE
5               Bern             Switzerland                      Bern      CH
6         Bratislava                Slovakia                Bratislava      SK
7           Brussels                 Belgium                  Brussels      BE
8          Bucharest                 Romania                 Bucharest      RO
9           Budapest                 Hungary                  Budapest      HU
10          Chișinău                 Moldova                  Chișinău      MD
11        Copenhagen                 Denmark                       NaN      DK
12            Dublin                 Ireland                    Dublin      IE
13          Helsinki                 Finland                  Helsinki      FI
14              Kyiv                 Ukraine                      Kyiv      UA
15            Lisbon                Portugal                    Lisbon      PT
16         Ljubljana                Slovenia                 Ljubljana      SI
17            London          United Kingdom                    London      GB
18        Luxembourg              Luxembourg    Luxembourg, Luxembourg      LU
19            Madrid                   Spain                    Madrid      ES
20             Minsk                 Belarus                     Minsk      BY
21              Oslo                  Norway                      Oslo      NO
22             Paris                  France                     Paris      FR
23         Podgorica              Montenegro                 Podgorica      ME
24            Prague          Czech Republic                    Prague      CZ
25          Pristina                  Kosovo                  Pristina      RS
26         Reykjavík                 Iceland                 Reykjavík      IS
27              Riga                  Latvia                      Riga      LV
28              Rome                   Italy                      Rome      IT
29          Sarajevo  Bosnia and Herzegovina                  Sarajevo      BA
30            Skopje         North Macedonia                    Skopje      MK
31             Sofia                Bulgaria                     Sofia      BG
32         Stockholm                  Sweden                 Stockholm      SE
33           Tallinn                 Estonia                   Tallinn      EE
34            Tirana                 Albania                    Tirana      AL
35            Vienna                 Austria                    Vienna      AT
36           Vilnius               Lithuania                   Vilnius      LT
37            Warsaw                  Poland                    Warsaw      PL
38            Zagreb                 Croatia               Zagreb city      HR

In [20]:
capitals_with_pop = capitals.merge(
    un_list[['city', 'population']],
    left_on = 'name_en',
    right_on = 'city',
    how = 'left'
).drop(columns = ['city'])
capitals_with_pop

,name_en,country_en,nominatim_query,alpha-2,population
0,Amsterdam,Netherlands,"Amsterdam, North Holland",NL,821752.0
1,Andorra la Vella,Andorra,Andorra la Vella,AD,NaN
2,Athens,Greece,Municipality of Athens,GR,664046.0
3,Belgrade,Serbia,Belgrade,RS,1382045.0
4,Berlin,Germany,Berlin,DE,3644826.0
5,Bern,Switzerland,Bern,CH,134290.0
6,Bratislava,Slovakia,Bratislava,SK,435296.0
7,Brussels,Belgium,Brussels,BE,174383.0
8,Bucharest,Romania,Bucharest,RO,1722865.0
9,Budapest,Hungary,Budapest,HU,1737026.0
10,Chișinău,Moldova,Chișinău,MD,339079.0
11,Copenhagen,Denmark,NaN,DK,638790.0
12,Dublin,Ireland,Dublin,IE,544107.0
13,Helsinki,Finland,Helsinki,FI,656920.0
14,Kyiv,Ukraine,Kyiv,UA,2910994.0
15,Lisbon,Portugal,Lisbon,PT,545142.0
16,Ljubljana,Slovenia,Ljubljana,SI,285604.0
17,London,United Kingdom,London,GB,8135667.0
18,Luxembourg,Luxembourg,"Luxembourg, Luxembourg",LU,128494.0
19,Madrid,Spain,Madrid,ES,3277451.0
20,Minsk,Belarus,Minsk,BY,2020133.0
21,Oslo,Norway,Oslo,NO,681067.0
22,Paris,France,Paris,FR,2206488.0
23,Podgorica,Montenegro,Podgorica,ME,185937.0
24,Prague,Czech Republic,Prague,CZ,1301432.0
25,Pristina,Kosovo,Pristina,RS,NaN
26,Reykjavík,Iceland,Reykjavík,IS,129964.0
27,Riga,Latvia,Riga,LV,614618.0
28,Rome,Italy,Rome,IT,2759629.0
29,Sarajevo,Bosnia and Herzegovina,Sarajevo,BA,NaN
30,Skopje,North Macedonia,Skopje,MK,546824.0
31,Sofia,Bulgaria,Sofia,BG,1221785.0
32,Stockholm,Sweden,Stockholm,SE,789024.0
33,Tallinn,Estonia,Tallinn,EE,437817.0
34,Tirana,Albania,Tirana,AL,418495.0
35,Vienna,Austria,Vienna,AT,1897491.0
36,Vilnius,Lithuania,Vilnius,LT,546155.0
37,Warsaw,Poland,Warsaw,PL,1792692.0
38,Zagreb,Croatia,Zagreb city,HR,790017.0

In [21]:
capitals_with_pop.at[1, 'population'] = 22205   # From https://unstats.un.org/unsd/demographic-social/products/dyb/documents/DYB2022/table08.pdf
capitals_with_pop.at[25, 'population'] = 161751 # From https://en.wikipedia.org/wiki/List_of_towns_and_cities_with_100,000_or_more_inhabitants
capitals_with_pop.at[29, 'population'] = 348363 # From https://en.wikipedia.org/wiki/List_of_towns_and_cities_with_100,000_or_more_inhabitants
capitals_with_pop

,name_en,country_en,nominatim_query,alpha-2,population
0,Amsterdam,Netherlands,"Amsterdam, North Holland",NL,821752.0
1,Andorra la Vella,Andorra,Andorra la Vella,AD,22205.0
2,Athens,Greece,Municipality of Athens,GR,664046.0
3,Belgrade,Serbia,Belgrade,RS,1382045.0
4,Berlin,Germany,Berlin,DE,3644826.0
5,Bern,Switzerland,Bern,CH,134290.0
6,Bratislava,Slovakia,Bratislava,SK,435296.0
7,Brussels,Belgium,Brussels,BE,174383.0
8,Bucharest,Romania,Bucharest,RO,1722865.0
9,Budapest,Hungary,Budapest,HU,1737026.0
10,Chișinău,Moldova,Chișinău,MD,339079.0
11,Copenhagen,Denmark,NaN,DK,638790.0
12,Dublin,Ireland,Dublin,IE,544107.0
13,Helsinki,Finland,Helsinki,FI,656920.0
14,Kyiv,Ukraine,Kyiv,UA,2910994.0
15,Lisbon,Portugal,Lisbon,PT,545142.0
16,Ljubljana,Slovenia,Ljubljana,SI,285604.0
17,London,United Kingdom,London,GB,8135667.0
18,Luxembourg,Luxembourg,"Luxembourg, Luxembourg",LU,128494.0
19,Madrid,Spain,Madrid,ES,3277451.0
20,Minsk,Belarus,Minsk,BY,2020133.0
21,Oslo,Norway,Oslo,NO,681067.0
22,Paris,France,Paris,FR,2206488.0
23,Podgorica,Montenegro,Podgorica,ME,185937.0
24,Prague,Czech Republic,Prague,CZ,1301432.0
25,Pristina,Kosovo,Pristina,RS,161751.0
26,Reykjavík,Iceland,Reykjavík,IS,129964.0
27,Riga,Latvia,Riga,LV,614618.0
28,Rome,Italy,Rome,IT,2759629.0
29,Sarajevo,Bosnia and Herzegovina,Sarajevo,BA,348363.0
30,Skopje,North Macedonia,Skopje,MK,546824.0
31,Sofia,Bulgaria,Sofia,BG,1221785.0
32,Stockholm,Sweden,Stockholm,SE,789024.0
33,Tallinn,Estonia,Tallinn,EE,437817.0
34,Tirana,Albania,Tirana,AL,418495.0
35,Vienna,Austria,Vienna,AT,1897491.0
36,Vilnius,Lithuania,Vilnius,LT,546155.0
37,Warsaw,Poland,Warsaw,PL,1792692.0
38,Zagreb,Croatia,Zagreb city,HR,790017.0

## Merge capitals qith non-capitals with over 100k population

In [23]:
capitalsand100000pop = pd.concat(
    [capitals_with_pop, cities_100000pop]
).sort_values(by = 'name_en')
capitalsand100000pop

               name_en   country_en    nominatim_query alpha-2  population
0               Aachen      Germany             Aachen      DE    247380.0
1      Aix-En-Provence       France    Aix-En-Provence      FR    142668.0
2    Alcalá De Henares        Spain  Alcalá De Henares      ES    195570.0
3             Alchevsk      Ukraine           Alchevsk      UA    105580.0
4           Alcobendas        Spain         Alcobendas      ES    116895.0
..                 ...          ...                ...     ...         ...
355       Zielona Góra       Poland       Zielona Góra      PL    141631.0
356         Zoetermeer  Netherlands         Zoetermeer      NL    124025.0
357             Zurich  Switzerland             Zurich      CH    423193.0
358             Zwolle  Netherlands             Zwolle      NL    123861.0
359           Šiauliai    Lithuania           Šiauliai      LT    100653.0

[399 rows x 5 columns]

In [24]:
capitalsand100000pop.to_csv(
    "../cities/european_capitalsand100000pop.csv",
    sep = ";",
    index = False
)